# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5da76f2363c1b5fb6e225c9a5692d22cdf3edb7f4b69c286413d2bf035f54237134b89ec54bec881d76d1c906d0fd41d6da9a667e138de81bdb3b5d2bde881b8

test:
  secret_key_base: ccbfcd92430493b71841815c03e5dab2dade11591181347888edb1fa55776f182fd6a649b9d2cb6b4d1723f244db95e13d01cf12af6059863549dc23a58dc590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
